<?php

namespace AssociationBundle\Repository;

/**
 * demandeDeVolantaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demandeDeVolantaireRepository extends \Doctrine\ORM\EntityRepository
{
}
