<?php

namespace AssociationBundle\Repository;

/**
 * demandeDeDonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demandeDeDonRepository extends \Doctrine\ORM\EntityRepository
{
}
