<?php

namespace AssociationBundle\Repository;

/**
 * donRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class donRepository extends \Doctrine\ORM\EntityRepository
{
}
