<?php

namespace AssociationBundle\Repository;

/**
 * volantaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class volantaireRepository extends \Doctrine\ORM\EntityRepository
{
}
