<?php

namespace EventBundle\Repository;

/**
 * challengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class challengeRepository extends \Doctrine\ORM\EntityRepository
{
}
