<?php

namespace EventBundle\Repository;

/**
 * participationChRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class participationChRepository extends \Doctrine\ORM\EntityRepository
{
}
