base_homepage:
    path:     /
    defaults: { _controller: BaseBundle:Default:index }

base_contact:
    path:     /contact
    defaults: { _controller: BaseBundle:Default:contact }

admin_homepage:
    path:     /back
    defaults: { _controller: BaseBundle:Default:back }